### ISSUE TITLE
Support better way of using PowerShell scripts

### ISSUE THREAD

**Issue by undergroundwires** [undergroundwires/privacy.sexy#53]
# Summary

Writing PowerShell is  in [windows.yaml](https://github.com/undergroundwires/privacy.sexy/blob/0.9.0/src/application/collections/windows.yaml) not a clean and easy experience. It makes the contributor experience hard. It should be as easy as writing a "normal" powershell without thinking about call to `PowerShell`, escaping and inlining stuff.

# Progress

- [x] Allow functions to be able to call each other
- [x] Introduce piping support when doing variable substitution with initial pipe: `powershellEscapeInline`
- [x] Introduce `RunPowerShell` function and refactor all PowerShell scripts to use it.

# Background

## Problem

Using PowerShell code in [windows.yaml](https://github.com/undergroundwires/privacy.sexy/blob/0.9.0/src/application/collections/windows.yaml) is difficult, an example is [`UninstallStoreApp`](https://github.com/undergroundwires/privacy.sexy/blob/0.9.0/src/application/collections/windows.yaml#L4146-L4152) function that looks like this:

```batchfile
PowerShell -ExecutionPolicy Unrestricted -Command "
  $package = Get-AppxPackage -AllUsers '{{ $packageName }}';
  if (!$package) {
    Write-Error \"Cannot reinstall '{{ $packageName }}'\" -ErrorAction Stop
  }
  $manifest = $package.InstallLocation + '\AppxManifest.xml';
  Add-AppxPackage -DisableDevelopmentMode -Register \"$manifest\" "
```

The problems are (as we are using batchfile to call powershell):

- The whole PowerShell string must be a single line, and therefore each line must end with `;`
- Double quotes in the string must be escaped using e.g. `\"`

This results in hard development and testing experience when working with PowerShell scripts.

## Solution

A solution should allow writing PowerShell that can be easily executed without any changes to the script. No escapes, no semicolons.

We would allow [yaml-defined functions](https://github.com/undergroundwires/privacy.sexy/blob/0.9.0/docs/collection-files.md#function) to call each other then we could separate out the part where `PowerShell -ExecutionPolicy Unrestricted -Command "..code"` happens.

For escaping backslash, and removing multilines and adding semicolons we could add some kind of "piping" support in our yaml-defined functions that would look like this. There are two alternatives of doing that:

1. Introducing "replace" pipe command: e.g. `PowerShell -ExecutionPolicy Unrestricted -Command "{{ $code | replace '\n' ';' | replace '"' '\"' }}"`.
2. Introducing `powershellEscapeInline` pipe: e.g. `PowerShell -ExecutionPolicy Unrestricted -Command "{{ $code | powershellEscapeInline }}"`

The first solution gives insights about what it exactly is going but, but it might better to go with back-end defined `powershellEscapeInline` as inlining PowerShell could have more minifications and details to it.

So in the end the solution would look something like:

```yaml
functions:
    -
        name: UninstallStoreApp
        parameters: [ packageName ]
        call:
            function: RunPowerShell
            parameters:
                code: |-
                    '{{ $packageName }}' | Remove-AppxPackage
                revertCode: |-
                    $package = Get-AppxPackage -AllUsers '{{ $packageName }}'
                    if (!$package) {
                        Write-Error "Cannot reinstall '{{ $packageName }}'"" -ErrorAction Stop
                    }
                    $manifest = $package.InstallLocation + '\AppxManifest.xml'
                    Add-AppxPackage -DisableDevelopmentMode -Register "$manifest"
    -
        name: RunPowerShell
        parameters: [ code, revertCode ]
        code: PowerShell -ExecutionPolicy Unrestricted -Command "{{ $code | powershellEscapeInline }}"
        revertCode: PowerShell -ExecutionPolicy Unrestricted -Command "{{ $revertCode | powershellEscapeInline }}"
```
